/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexionBD.GenerosDAO;
import conexionBD.PrestamoDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Generos;
import modelo.Prestamo;

/**
 *
 * @author erik
 */
public class VistaPrestamo extends javax.swing.JFrame {
    
    PrestamoDAO pdao = new PrestamoDAO();
    conexionBD.conexionBD co;
    JOptionPane pane;
    Prestamo p = new Prestamo();
    GenerosDAO gnd = new GenerosDAO();
     ArrayList lista = new ArrayList();
    
    /**
     * Creates new form VistaPrestamo
     */
    public VistaPrestamo() {
        initComponents();
    }
    
    public VistaPrestamo(conexionBD.conexionBD co){
        this.co = co;
        initComponents();
        //actualizarTabla();
        dias(cmb_dias_devolucion);
        años(cmb_year_devolucion);
        dias(cmb_dias_prestamo);
        años(cmb_year_prestamo);
        yearsCombo(cmb_libro_year);
        generoCombo(cmb_genero);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cj_libro_id = new javax.swing.JTextField();
        cj_lector_id = new javax.swing.JTextField();
        cmb_dias_prestamo = new javax.swing.JComboBox<>();
        cmb_mes_prestamo = new javax.swing.JComboBox<>();
        cmb_year_prestamo = new javax.swing.JComboBox<>();
        cmb_dias_devolucion = new javax.swing.JComboBox<>();
        cmb_meses_devolucion = new javax.swing.JComboBox<>();
        cmb_year_devolucion = new javax.swing.JComboBox<>();
        cmb_multa = new javax.swing.JComboBox<>();
        rd_Libro_id = new javax.swing.JRadioButton();
        rd_Lector_id = new javax.swing.JRadioButton();
        rd_fecha_prestamo = new javax.swing.JRadioButton();
        rd_fecha_devolucion = new javax.swing.JRadioButton();
        rd_multa = new javax.swing.JRadioButton();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        btn_vista = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_prestamo = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        ck_titulo = new javax.swing.JCheckBox();
        ck_editorial = new javax.swing.JCheckBox();
        ck_year = new javax.swing.JCheckBox();
        ck_ISBN = new javax.swing.JCheckBox();
        ck_tipo_libro = new javax.swing.JCheckBox();
        ck_genero = new javax.swing.JCheckBox();
        cmb_libro_year = new javax.swing.JComboBox<>();
        cmb_tipoLibro = new javax.swing.JComboBox<>();
        cmb_genero = new javax.swing.JComboBox<>();
        cj_titulo = new javax.swing.JTextField();
        cj_editorial = new javax.swing.JTextField();
        cj_isbn = new javax.swing.JTextField();
        ck_lector_id = new javax.swing.JCheckBox();
        ck_fecha_prestamo = new javax.swing.JCheckBox();
        ck_fecha_devolucion = new javax.swing.JCheckBox();
        ch_multa = new javax.swing.JCheckBox();
        ck_libro_id_prestamo = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaFiltro = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btn_busqueda_avanzada = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(133, 205, 186));

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel1.setText("Prestamo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        jButton1.setText("Regresar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        cmb_mes_prestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        cmb_meses_devolucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        cmb_multa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        rd_Libro_id.setText("Libro Id");

        rd_Lector_id.setText("Lector Id");

        buttonGroup1.add(rd_fecha_prestamo);
        rd_fecha_prestamo.setText("Fecha Prestamo");

        buttonGroup1.add(rd_fecha_devolucion);
        rd_fecha_devolucion.setText("Fecha Devolucion");

        buttonGroup1.add(rd_multa);
        rd_multa.setText("Multa");

        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_vista.setText("Vista");
        btn_vista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd_Libro_id)
                    .addComponent(rd_Lector_id)
                    .addComponent(rd_fecha_prestamo)
                    .addComponent(rd_fecha_devolucion)
                    .addComponent(rd_multa)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_agregar)
                            .addComponent(btn_modificar))))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_buscar)
                        .addGap(67, 67, 67)
                        .addComponent(btn_vista))
                    .addComponent(btn_eliminar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(cj_libro_id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(cmb_dias_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmb_mes_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cj_lector_id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(cmb_dias_devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmb_meses_devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cmb_multa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmb_year_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmb_year_devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(110, 110, 110)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cj_libro_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rd_Libro_id))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cj_lector_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rd_Lector_id))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_dias_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_mes_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_year_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rd_fecha_prestamo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_dias_devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_meses_devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_year_devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rd_fecha_devolucion))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_multa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rd_multa))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificar)
                    .addComponent(btn_buscar)
                    .addComponent(btn_vista))
                .addGap(33, 33, 33))
        );

        t_prestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(t_prestamo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ck_titulo.setText("Titulo");

        ck_editorial.setText("Editorial");

        ck_year.setText("Año");

        ck_ISBN.setText("ISBN");

        ck_tipo_libro.setText("Tipo Libro");

        ck_genero.setText("Genero");

        cmb_libro_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_tipoLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ck_lector_id.setText("Lector Id");

        ck_fecha_prestamo.setText("Fecha Prestamo");

        ck_fecha_devolucion.setText("Fecha Devolucion");

        ch_multa.setText("Multa");

        ck_libro_id_prestamo.setText("Libro Id");

        listaFiltro.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Libro Id", "Lector Id", "Fecha Prestamo", "Fecha Devolucion", "Multa", "Titulo", "Editorial", "Año", "ISBN", "Tipo Libro", "Genero" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaFiltroMouseClicked(evt);
            }
        });
        listaFiltro.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaFiltroValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaFiltro);

        jLabel2.setText("Filtro de busqueda");

        btn_busqueda_avanzada.setText("Busqueda Avanzada");
        btn_busqueda_avanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busqueda_avanzadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(ck_libro_id_prestamo)
                .addGap(0, 310, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ck_titulo)
                            .addComponent(ck_editorial))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cj_editorial)
                            .addComponent(cj_titulo)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ck_year)
                            .addComponent(ck_tipo_libro)
                            .addComponent(ck_genero)
                            .addComponent(ck_ISBN))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cj_isbn)
                            .addComponent(cmb_genero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_tipoLibro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_libro_year, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btn_busqueda_avanzada))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ck_lector_id)
                            .addComponent(ck_fecha_prestamo)
                            .addComponent(ck_fecha_devolucion)
                            .addComponent(ch_multa)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ck_libro_id_prestamo)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck_titulo)
                    .addComponent(cj_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ck_lector_id))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck_editorial)
                    .addComponent(cj_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ck_fecha_prestamo))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck_year)
                    .addComponent(cmb_libro_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ck_fecha_devolucion))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck_ISBN)
                    .addComponent(cj_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch_multa))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_tipoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ck_tipo_libro))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ck_genero)
                            .addComponent(cmb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_busqueda_avanzada))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_busqueda_avanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busqueda_avanzadaActionPerformed
        // TODO add your handling code here:
        pdao.busquedaAvanzada(elegirAtributos(restablecerComponentes(ck_libro_id_prestamo,ch_multa,ck_ISBN,ck_editorial,ck_fecha_devolucion,ck_fecha_prestamo
        ,ck_tipo_libro,ck_titulo,ck_year,ck_genero,ck_lector_id)), filtroLista(listaFiltro),co,t_prestamo);
    }//GEN-LAST:event_btn_busqueda_avanzadaActionPerformed

    private void listaFiltroValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaFiltroValueChanged
        // TODO add your handling code here:
        if(listaFiltro.getSelectedValuesList().size() >= 3 ){
                listaFiltro.clearSelection();
        }
    }//GEN-LAST:event_listaFiltroValueChanged

    private void listaFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaFiltroMouseClicked
        // TODO add your handling code here:
        /*if(listaFiltro.getSelectedValuesList().size() > 3 ){
                listaFiltro.clearSelection();
        }*/
    }//GEN-LAST:event_listaFiltroMouseClicked

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        boolean a = false,b = false;
        String yp = "",mp = "",dp = "",y = "",m = "",d = "",fp = "",fd="";
        
        if(!cj_libro_id.getText().equals("")){
            if(Character.isDigit(cj_libro_id.getText().charAt(0))){
                a = true;
            }
            else{
                pane.showMessageDialog(pane, "el id libro no es numerico");
            }
        }
        else{
            pane.showMessageDialog(pane, "la caja id libro esta vacia");
        }
        if(!cj_lector_id.getText().equals("")){
            if(Character.isDigit(cj_lector_id.getText().charAt(0))){
                b = true;
            }
            else{
                pane.showMessageDialog(pane, "el id lector no es numerico");
            }
        }
        else{
            pane.showMessageDialog(pane, "la caja id lector esta vacia");
        }
        
        if(a && b){
            
            p.setId_libro_prestamo(Integer.valueOf(cj_libro_id.getText()));
            p.setId_lector_prestamo(Integer.valueOf(cj_lector_id.getText()));
            yp = String.valueOf(cmb_year_prestamo.getSelectedItem());
            mp = String.valueOf(meses(String.valueOf(cmb_mes_prestamo.getSelectedItem())));
            dp = String.valueOf(cmb_dias_prestamo.getSelectedItem());
            fp = yp+"-"+mp+"-"+dp;
            p.setFecha_prestamo(fp);
            y = String.valueOf(cmb_year_devolucion.getSelectedItem());
            m = String.valueOf(meses(String.valueOf(cmb_meses_devolucion.getSelectedItem())));
            d = String.valueOf(cmb_dias_devolucion.getSelectedItem());
            fd = y+"-"+m+"-"+d;
            p.setFecha_devolucion(fd);
            p.setMulta(Boolean.valueOf(multa(String.valueOf(cmb_multa.getSelectedItem()))));
            System.out.println("vista.VistaPrestamo.btn_agregarActionPerformed() "+p);
            pdao.agregarPrestamo(p,co);
            
        }
        
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        boolean a = false,b = false;
        
        if(rd_Lector_id.isSelected() && rd_Libro_id.isSelected()){
            if(!cj_libro_id.getText().equals("")){
                if(Character.isDigit(cj_libro_id.getText().charAt(0))){
                    a = true;
                }
                else{
                    pane.showMessageDialog(pane, "el id libro no es numerico");
                }
            }
        else{
            pane.showMessageDialog(pane, "la caja id libro esta vacia");
        }
            if(!cj_lector_id.getText().equals("")){
                if(Character.isDigit(cj_lector_id.getText().charAt(0))){
                    b = true;
                }
                else{
                    pane.showMessageDialog(pane, "el id lector no es numerico");
                }
            }
        else{
            pane.showMessageDialog(pane, "la caja id lector esta vacia");
            }
        }
        else{
            pane.showMessageDialog(pane, "seleccione los radiobutton id");
        }
        
        if(a && b){
            p.setId_libro_prestamo(Integer.parseInt(cj_libro_id.getText()));
            p.setId_lector_prestamo(Integer.parseInt(cj_lector_id.getText()));
            
            pdao.eliminarPrestamo(p.getId_libro_prestamo(), p.getId_lector_prestamo(), co);
        }
        
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
        String yp = "",mp = "",dp = "",y = "",m = "",d = "",fp = "",fd="";
        if(rd_Lector_id.isSelected() && rd_Libro_id.isSelected()){
            if(!cj_libro_id.getText().equals("") && !cj_lector_id.getText().equals("")){
                if(Character.isDigit(cj_libro_id.getText().charAt(0)) && Character.isDigit(cj_lector_id.getText().charAt(0))){
                    p.setId_libro_prestamo(Integer.parseInt(cj_libro_id.getText()));
                    p.setId_lector_prestamo(Integer.parseInt(cj_lector_id.getText()));
                    yp = String.valueOf(cmb_year_prestamo.getSelectedItem());
                    mp = String.valueOf(meses(String.valueOf(cmb_mes_prestamo.getSelectedItem())));
                    dp = String.valueOf(cmb_dias_prestamo.getSelectedItem());
                    fp = yp+"-"+mp+"-"+dp;
                    p.setFecha_prestamo(fp);
                    y = String.valueOf(cmb_year_devolucion.getSelectedItem());
                    m = String.valueOf(meses(String.valueOf(cmb_meses_devolucion.getSelectedItem())));
                    d = String.valueOf(cmb_dias_devolucion.getSelectedItem());
                    fd = y+"-"+m+"-"+d;
                    p.setFecha_devolucion(fd);
                    p.setMulta(Boolean.valueOf(multa(String.valueOf(cmb_multa.getSelectedItem()))));
                    
                    pdao.modificarPrestamo(p, co);
                }
                else{
                    pane.showMessageDialog(pane, "el id libro no es numerico");
                }
            }
        else{
            pane.showMessageDialog(pane, "la caja id libro esta vacia");
        }
        
       /* if(a && b){
            p = pdao.ModificaPrestamo(p.getId_libro_prestamo(), p.getId_lector_prestamo(), co);
            cj_libro_id.setText(String.valueOf(p.getId_libro_prestamo()));
         */   
        }
        else{
            pane.showMessageDialog(pane, "seleccione los radiobutton id");
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        if(rd_Libro_id.isSelected()){
            if(!cj_libro_id.getText().equals("")){
                if(Character.isDigit(cj_libro_id.getText().charAt(0))){
                    pdao.consultaLector("libros_id", cj_libro_id.getText(), t_prestamo, co);
                }
                else{
                    pane.showMessageDialog(pane, "caja id libro no es un digito");
                }
            }
            else{
                pane.showMessageDialog(pane, "caja id libro esta vacia");
            }  
        }
        else if(rd_Lector_id.isSelected()){ 
            if(!cj_lector_id.getText().equals("")){
                if(Character.isDigit(cj_lector_id.getText().charAt(0))){
                    pdao.consultaLector("lector_id", cj_lector_id.getText(), t_prestamo, co);
                }
                else{
                    pane.showMessageDialog(pane, "caja id lector no es un digito");
                }
            }
            else{
                pane.showMessageDialog(pane, "caja id lector esta vacia");
            }
        }
        else if(rd_Lector_id.isSelected() && rd_Libro_id.isSelected()){
            if(!cj_lector_id.getText().equals("") && !cj_libro_id.getText().equals("")){
                if(Character.isDigit(cj_lector_id.getText().charAt(0)) && Character.isDigit(cj_libro_id.getText().charAt(0))){
                    pdao.consultaLector("lector_id", cj_lector_id.getText(), t_prestamo, co);
                }
                else{
                    pane.showMessageDialog(pane, "caja id lector o id libro no es un digito");
                }
            }
            else{
                pane.showMessageDialog(pane, "caja id lector o id libro esta vacia");
            }
        }
        else if(rd_fecha_devolucion.isSelected()){
            String y = String.valueOf(cmb_year_devolucion.getSelectedItem());
            String m = String.valueOf(cmb_meses_devolucion.getSelectedItem());
            String d = String.valueOf(cmb_dias_devolucion.getSelectedItem());
            String fecha = y+"-"+m+"-"+d;
            pdao.consultaLector("fecha_devolucion", fecha, t_prestamo, co);
        }
        else if(rd_fecha_prestamo.isSelected()){
            String y = String.valueOf(cmb_year_prestamo.getSelectedItem());
            String m = String.valueOf(cmb_mes_prestamo.getSelectedItem());
            String d = String.valueOf(cmb_dias_prestamo.getSelectedItem());
            String fecha = y+"-"+m+"-"+d;
            pdao.consultaLector("fecha_prestamo", fecha, t_prestamo, co);
        }
        else if(rd_multa.isSelected()){
            pdao.consultaLector("multa", multa(String.valueOf(cmb_multa.getSelectedItem())), t_prestamo, co);
        }
        else {
            pane.showMessageDialog(pane, "seleccione algun radiobutton");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_vistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vistaActionPerformed
        // TODO add your handling code here:
        view v = new view(co);
        v.setVisible(true);
    }//GEN-LAST:event_btn_vistaActionPerformed

    public ArrayList filtroLista(JList lista){
        ArrayList listaFiltros = new ArrayList();
        //lista.getSelectedValuesList().size();
        for (int i = 0; i < lista.getSelectedValuesList().size(); i++) {
            switch(String.valueOf(lista.getSelectedValuesList().get(i))){
                case "Libro Id":
                    listaFiltros.add("libro_id = "+cj_libro_id.getText());
                    break;
                case "Lector Id":
                    //cadena1 = "Lector_Id";
                    listaFiltros.add("Lector_Id = "+cj_lector_id.getText());
                    break;
                case "Fecha Prestamo":
                    //cadena2 = "fecha_prestamo";
                    listaFiltros.add("fecha_prestamo");
                    break;
                case "Fecha Devolucion":
                    //cadena3 = "fecha_devolucion";
                    listaFiltros.add("fecha_devolucion");
                    break;
                case "Multa":
                    //cadena4 = "Multa";
                    listaFiltros.add("Multa = '"+cmb_multa.getSelectedItem()+"'");
                    break;
                case "Titulo":
                    //cadena4 = "Multa";
                    listaFiltros.add("Titulo = '"+cj_titulo.getText()+"'");
                    break;
                case "Editorial":
                    //cadena4 = "Multa";
                    listaFiltros.add("Editorial = '"+cj_editorial.getText()+"'");
                    break;
                case "Año":
                    //cadena4 = "Multa";
                    listaFiltros.add("Year = '"+cmb_libro_year.getSelectedItem()+"'");
                    break;
                case "ISBN":
                    //cadena4 = "Multa";
                    listaFiltros.add("ISBN = '"+cj_isbn.getText()+"'");
                    break;
                case "Tipo Libro":
                    //cadena4 = "Multa";
                    listaFiltros.add("tipo_libro = '"+cmb_tipoLibro.getSelectedItem()+"'");
                    break;
                case "Genero":
                    //cadena4 = "Multa";
                    listaFiltros.add("Genero = '"+cmb_genero.getSelectedItem()+"'");
                    break;
                default:
                    //cadenaDefault = "*";
                    listaFiltros.add("*");
            }
            
        }
        System.out.println("vista.VistaPrestamo.filtroLista() --> "+listaFiltros);
        return listaFiltros;
    }
    
    public ArrayList restablecerComponentes(JComponent...componentes) {
        ArrayList listaComponentes = new ArrayList();
        for (int i = 0; i < componentes.length; i++) {
            if(((JCheckBox)componentes[i]).isSelected()){
                //((JCheckBox)componentes[i]).getText();
                listaComponentes.add(((JCheckBox)componentes[i]).getText());
                
            }
	}
        
        System.out.println("vista.VistaPrestamo.restablecerComponentes() "+listaFiltro.getSelectedValuesList());
        return listaComponentes;
    }
    
    public ArrayList elegirAtributos(ArrayList lista){
        
        ArrayList listaSQL = new ArrayList();
        for (int i = 0; i < lista.size(); i++) {
            switch(String.valueOf(lista.get(i))){
                case "Libro Id":
                    //cadena = "Libro_Id";
                    listaSQL.add("Libro_Id");
                    break;
                case "Lector Id":
                    //cadena1 = "Lector_Id";
                    listaSQL.add("Lector_Id");
                    break;
                case "Fecha Prestamo":
                    //cadena2 = "fecha_prestamo";
                    listaSQL.add("fecha_prestamo");
                    break;
                case "Fecha Devolucion":
                    //cadena3 = "fecha_devolucion";
                    listaSQL.add("fecha_devolucion");
                    break;
                case "Multa":
                    //cadena4 = "Multa";
                    listaSQL.add("Multa");
                    break;
                case "Titulo":
                    //cadena4 = "Multa";
                    listaSQL.add("Titulo");
                    break;
                case "Editorial":
                    //cadena4 = "Multa";
                    listaSQL.add("Editorial");
                    break;
                case "Año":
                    //cadena4 = "Multa";
                    listaSQL.add("Year");
                    break;
                case "ISBN":
                    //cadena4 = "Multa";
                    listaSQL.add("ISBN");
                    break;
                case "Tipo Libro":
                    //cadena4 = "Multa";
                    listaSQL.add("tipo_libro");
                    break;
                case "Genero":
                    //cadena4 = "Multa";
                    listaSQL.add("Genero");
                    break;
                case "":
                    listaSQL.add("*");
                    break;
                default:
                    //cadenaDefault = "*";
                    listaSQL.add("*");
            }
            //if(!listaSQL.get(i).equals("")){
            //    cadenaSQL += String.valueOf(listaSQL.get(i));
            //}
            //System.out.println("vista.VistaPrestamo.elegir() listaSQL "+listaSQL.get(i));
            
        }
        System.out.println("vista.VistaPrestamo.elegir() "+listaSQL);
        return listaSQL;
    }
    
    public void dias(JComboBox combo){
        for (int i = 1; i <= 31; i++) {
            combo.addItem(i);
        }
    }
    
    public void años(JComboBox combo){
        //Date f = new Date();
        Calendar c = Calendar.getInstance();
        int annio = c.get(Calendar.YEAR);
        for (int i = 1919; i <= annio; i++) {
            combo.addItem(i);
        }
    }
    
    public void yearsCombo(JComboBox combo){
        Calendar c = Calendar.getInstance();
        int annio = c.get(Calendar.YEAR);
        for (int i = 1400; i <= annio; i++) {
            combo.addItem(i);
        }
    }
    
    public void generoCombo(JComboBox comboG){
        lista = (ArrayList) gnd.buscarAlumnos(this.co);
        Generos nuevo = new Generos();
        //nuevo = lista.set(, menu)
        for (int i = 0; i < lista.size(); i++) {
            //Object get = lst.get(i);
            nuevo = (Generos) lista.set(i, gnd);
            //comboG.addItem(lista.get(i));
            comboG.addItem(nuevo.getGenero());
        }
    }
    
    public int meses(String mes){
        int month = 0;
        switch(mes){
            case "Enero":
                month = 1;
                break;
            case "Febrero":
                month = 2;
                break;
            case "Marzo":
                month = 3;
                break;
            case "Abril":
                month = 4;
                break;
            case "Mayo":
                month = 5;
                break;
            case "Junio":
                month = 6;
                break;
            case "Julio":
                month = 7;
                break;
            case "Agosto":
                month = 8;
                break;
            case "Septiembre":
                month = 9;
                break;
            case "Octubre":
                month = 10;
                break;
            case "Noviembre":
                month = 11;
                break;    
            case "Diciembre":
                month = 12;
                break;
            default:
                month = 0;
                break;
        }
        return month;
    }
    
    public String multa(String multa){
        String retorno = "";
        switch(multa){
            case "Si":
                retorno = "true";
                break;
            case "No":
                retorno = "false";
                break;
        }
        return retorno;
    }
    
     public void actualizarTabla() {
		final String TABLA_LIBRO = "Prestamo";
		//conexionBD conexion = new conexionBD();

		String driver = "com.ibm.db2.jcc.DB2Driver";
		String url = "jdbc:db2://localhost:50001/library";
		//String user = "root";
		//String password = "root1";
		String query = "SELECT * FROM " + TABLA_LIBRO;

		ResultSetTableModel2 modelo = null;
		try {
			modelo = new ResultSetTableModel2(driver, url, co.getUsuario(), co.getContra(), query);
		} catch (SQLException e1) {
			e1.printStackTrace();
		} catch (ClassNotFoundException e1) {
			e1.printStackTrace();
		}
		
            t_prestamo.setModel(modelo);
	}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_busqueda_avanzada;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_vista;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ch_multa;
    private javax.swing.JTextField cj_editorial;
    private javax.swing.JTextField cj_isbn;
    private javax.swing.JTextField cj_lector_id;
    private javax.swing.JTextField cj_libro_id;
    private javax.swing.JTextField cj_titulo;
    private javax.swing.JCheckBox ck_ISBN;
    private javax.swing.JCheckBox ck_editorial;
    private javax.swing.JCheckBox ck_fecha_devolucion;
    private javax.swing.JCheckBox ck_fecha_prestamo;
    private javax.swing.JCheckBox ck_genero;
    private javax.swing.JCheckBox ck_lector_id;
    private javax.swing.JCheckBox ck_libro_id_prestamo;
    private javax.swing.JCheckBox ck_tipo_libro;
    private javax.swing.JCheckBox ck_titulo;
    private javax.swing.JCheckBox ck_year;
    private javax.swing.JComboBox<String> cmb_dias_devolucion;
    private javax.swing.JComboBox<String> cmb_dias_prestamo;
    private javax.swing.JComboBox<String> cmb_genero;
    private javax.swing.JComboBox<String> cmb_libro_year;
    private javax.swing.JComboBox<String> cmb_mes_prestamo;
    private javax.swing.JComboBox<String> cmb_meses_devolucion;
    private javax.swing.JComboBox<String> cmb_multa;
    private javax.swing.JComboBox<String> cmb_tipoLibro;
    private javax.swing.JComboBox<String> cmb_year_devolucion;
    private javax.swing.JComboBox<String> cmb_year_prestamo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JList<String> listaFiltro;
    private javax.swing.JRadioButton rd_Lector_id;
    private javax.swing.JRadioButton rd_Libro_id;
    private javax.swing.JRadioButton rd_fecha_devolucion;
    private javax.swing.JRadioButton rd_fecha_prestamo;
    private javax.swing.JRadioButton rd_multa;
    private javax.swing.JTable t_prestamo;
    // End of variables declaration//GEN-END:variables
}
